# Generated by Django 5.2.12 on 2026-03-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_products', to='course.course')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_courses', to='product.product')),
            ],
            options={
                'db_table': 'product_course_mapping',
                'unique_together': {('product', 'course')},
            },
        ),
    ]
